### ISSUE TITLE
Update to profits, purpose, and impact animation

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#17]
The team would like to group the three shapes and rotate them before scrolling and aligning them horizontally, see animation below. 

https://user-images.githubusercontent.com/18393982/133512547-93f9418c-e92f-4de8-b38e-26c24a05008f.mp4

**Comment by jackmez** [comment]
Please can we also tighten space between the headline 'The ultimate alignment of profits, purpose, and impact.' closer to the three columns bellow.

**Comment by saiminh** [comment]
This is actually a big change in the animation structure. 
It was one linear timeline that could be played back and forth, but with the new circle dance in the middle, I have to split up the scroll effect into multiple timelines and try to connect them on scroll and track the positions and rotation of each of the polygons. Because unlike in a static animation, we don't know when the user will start scrolling again.
Before I put in the extra hours to make this happen, are you sure this is going to be right and impactful? I expect that most users will not stop scrolling and look at the headline for a while like you simulated in the video mockup, but instead scroll right past it, which will make this a far less smooth looking experience than in the mockup in most cases... 
Especially if you want to even further reduce the spacing between the headline and the columns endpoint, the scrolling sweet-spot where this circle dance animation is playing will be really small... 
I estimate this is a huge impact on extra work with a very small impact on presentation, so maybe we could mark this as nice-to-have or low priority?

**Comment by jackmez** [comment]
Leave it with me, I will have a think if there is another, similar solution that hopefully requires less re-working.
Let's mark as low-priority for now. cheers.

**Comment by saiminh** [comment]
OK so the animation logic stands, but it looks a bit different than in your AE mockup at the moment. 
The reason for that is that your polygons keep changing sizes and colors. (first design, current design, current live page and current AE mockup all have different sizes and colors) This makes the calculation of the coordinates for a harmonius triangle composition impossible.
 
Therefore I suggest you upload 3 polygons of identical height and width and we do the difference in scale (only the one on the left is slightly larger) within the animation. This way we can guarantee that they will always meet nicel in the middle and we can adjust the sizes of the endpoint in JS.

So again, to make the current status look good in the center-triangle position, use three polygon svgs of the same width and height.
