### ISSUE TITLE
Add Google analytics tracking ID

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#21]
I don't have the tracking ID yet but adding it here so we don't forget before launch.

**Comment by jackmez** [comment]
Hi Simon, 
Rosie sent these details over,

with the _Measurements ID:_
**G-BTHDQ2MN8L** 

Is this the same as the Tracking ID?

![GA](https://user-images.githubusercontent.com/18393982/135060842-2bb5f3b9-085a-480b-889e-c2bdaedb4677.png)

**Comment by jackmez** [comment]
Do we need more info here to set up Analytics?

**Comment by saiminh** [comment]
No this should be enough. I have implemented and tested it and the GA cookie can be set revoked with our cookie policy buttons. The only thing left to do is for the client to verify if it is working within their GA console. But only once they have switched the domain name of course.
From my experience it is good to check if the client understands that GA will only work if the user has opted in at the cookie policy popup, otherwise GA will never even load. I had clients that wanted GA to always work AND be GDPR compliant, which is of course impossible, but not everyone understands that. So maybe worth double checking before the client says 'it's not working correctly'...
