### ISSUE TITLE
Add slim version of font to CMS

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#4]
Can we add the slim version of the font to the site so we can select in the CMS if text should be, 'Neutral' or 'Slim'

[SyntheSans Slim-web.zip](https://github.com/saiminh/shynthesis-wptheme/files/7129928/SyntheSans.Slim-web.zip)

**Comment by saiminh** [comment]
Right now, there is actually ONLY the Slim Version on the site, Patrick asked me to swap Neutral for Slim and to only use that. I think it makes sense because these two fonts aren't different enough so they can be used as a strong emphasis and just for the use in some small and rare use cases, the extra 40KB are "too expensive"

**Comment by jackmez** [comment]
Agree, lets just keep it as it is then
