### ISSUE TITLE
Can we introduce a way to add a separator (or something similar) between sections to be able to create more space between sections?

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#9]
For example, I want to be able to pad these sections out much more (~200px) as well as in other places across the site

<img width="926" alt="Screenshot 2021-09-08 at 18 10 54" src="https://user-images.githubusercontent.com/18393982/132545566-1a12814b-17af-4594-9eae-064534275ae0.png">

**Comment by saiminh** [comment]
Spacers are a really bad practice. I know that a lot of page-builder tools have that, because it's an easy way to enable the user to create spacing without having to write any CSS.  

Creating an HTML DOM element just for the sake of adding spacing is against the concept of separating concerns (design is separate from content). It lowers accessibility and even if at first it seems convenient it WILL get extremely messy when trying to maintain the site later. Because now you have to maintain the look of the site in multiple places.

So I would really advise against that and have a design system and write CSS rules.

That being said, WordPress has a native Spacer block you can use if you really need to desperately create some space. Just add a new content block and search for 'Spacer' and there you have it. You can specify the height in pixels. Just be aware that this also applies to all screen sizes...

**Comment by saiminh** [comment]
See my notes in Slack, I have added some spacers at the place you specified above and you can easily add more wherever you want. That should enable you to make some quick spacing changes without having to write any code.
